/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    appeals: Appeal;
    'annual-reports': AnnualReport;
    remedies: Remedy;
    articles: Article;
    pages: Page;
    testimonials: Testimonial;
    'team-members': TeamMember;
    faqs: Faq;
    donations: Donation;
    pledges: Pledge;
    'assistance-requests': AssistanceRequest;
    programmes: Programme;
    teachers: Teacher;
    products: Product;
    ambassadors: Ambassador;
    orders: Order;
    media: Media;
    'newsletter-subscribers': NewsletterSubscriber;
    'contact-messages': ContactMessage;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    appeals: AppealsSelect<false> | AppealsSelect<true>;
    'annual-reports': AnnualReportsSelect<false> | AnnualReportsSelect<true>;
    remedies: RemediesSelect<false> | RemediesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    pledges: PledgesSelect<false> | PledgesSelect<true>;
    'assistance-requests': AssistanceRequestsSelect<false> | AssistanceRequestsSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    teachers: TeachersSelect<false> | TeachersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    ambassadors: AmbassadorsSelect<false> | AmbassadorsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Historical record of the 2023 appeals. New assistance is handled by the Empowerment Fund.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appeals".
 */
export interface Appeal {
  id: number;
  title: string;
  /**
   * URL segment. Generated from the title if left blank.
   */
  slug: string;
  /**
   * Default. Untick only with recorded written consent to publish the name.
   */
  isAnonymous?: boolean | null;
  category: 'medical' | 'financial' | 'shelter' | 'project';
  /**
   * Only with consent on file.
   */
  beneficiaryName?: string | null;
  /**
   * Category description shown instead of a name, e.g. "A revert sister".
   */
  anonymousLabel?: string | null;
  needDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  hospital?: string | null;
  /**
   * Amount in kobo (integer). ₦1,000 = 100000 kobo.
   */
  targetAmountKobo?: number | null;
  /**
   * Kobo. Incremented only by the verified Paystack webhook — never edited to flatter a shortfall.
   */
  raisedAmountKobo?: number | null;
  status: 'active' | 'closed' | 'partially-met';
  openedDate: string;
  closedDate?: string | null;
  /**
   * Only images with recorded consent. Check the consent flag on each item.
   */
  photos?: (number | Media)[] | null;
  updates?:
    | {
        date: string;
        title: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  closingReport?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers. Required — WCAG 2.1 AA.
   */
  alt: string;
  /**
   * Photographer or source, if attribution is owed.
   */
  credit?: string | null;
  /**
   * Tick ONLY if separate written consent to publish this person's image is on file (NDPA 2023). Beneficiary photos may not be published without it.
   */
  consentRecorded?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-reports".
 */
export interface AnnualReport {
  id: number;
  /**
   * e.g. 2023. One report per year.
   */
  fiscalYear: number;
  introduction?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Copy the Arabic verbatim from the source, diacritics intact. Never retype it.
   */
  quranVerse?: {
    arabic?: string | null;
    translation?: string | null;
    reference?: string | null;
  };
  /**
   * Names appear here only where consent is recorded; otherwise use a category description.
   */
  beneficiaries?:
    | {
        name: string;
        date: string;
        need: string;
        hospital?: string | null;
        /**
         * Amount in kobo (integer). ₦1,000 = 100000 kobo.
         */
        raisedKobo?: number | null;
        /**
         * Amount in kobo (integer). ₦1,000 = 100000 kobo.
         */
        targetKobo?: number | null;
        id?: string | null;
      }[]
    | null;
  surplusAssistances?:
    | {
        description: string;
        /**
         * Amount in kobo (integer). ₦1,000 = 100000 kobo.
         */
        amountKobo?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Amount in kobo (integer). ₦1,000 = 100000 kobo.
   */
  totalRaisedKobo: number;
  beneficiaryCount: number;
  closingNote?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The signed report as published, if there is one.
   */
  pdfUpload?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "remedies".
 */
export interface Remedy {
  id: number;
  name: string;
  /**
   * Arabic, with diacritics as in the book.
   */
  arabicName?: string | null;
  transliteration?: string | null;
  /**
   * URL segment. Generated from the title if left blank.
   */
  slug: string;
  quranVerse?: {
    arabic?: string | null;
    translation?: string | null;
    reference?: string | null;
  };
  /**
   * Full citation on every hadith. Never publish one without its source.
   */
  hadiths?:
    | {
        /**
         * Verbatim from the source. Diacritics preserved.
         */
        arabic: string;
        translation: string;
        source: string;
        /**
         * Grading and who graded it, where the book gives one.
         */
        gradingNote?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * From At-Tibb an-Nabawiyy, as quoted in the book.
   */
  ibnQayyimCommentary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  composition?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  traditionalUses?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cautions and contraindications. This page is not medical advice and makes no claim to cure.
   */
  precautions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 10–15 chapters are free; the rest sell the book.
   */
  isFree?: boolean | null;
  bookChapterRef?: string | null;
  /**
   * Optional cross-reference. The product page itself must carry no health claim.
   */
  relatedProduct?: (number | null) | Product;
  featuredImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * No health claims on product content — educational pages only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * URL segment. Generated from the title if left blank.
   */
  slug: string;
  /**
   * Describe the honey — source, colour, taste, pack. No claim that it treats, prevents or cures anything.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Honey is sold by volume, in litres.
   */
  volumeLitres: number;
  packSize?: string | null;
  /**
   * Amount in kobo (integer). ₦1,000 = 100000 kobo.
   */
  retailPriceKobo: number;
  /**
   * Amount in kobo (integer). ₦1,000 = 100000 kobo.
   */
  wholesalePriceKobo?: number | null;
  /**
   * Litres needed for wholesale pricing. Also the qualifying minimum for ambassador referrals.
   */
  minWholesaleLitres?: number | null;
  images?: (number | Media)[] | null;
  /**
   * NAFDAC registration number, where one is held.
   */
  nafdacNumber?: string | null;
  inStock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL segment. Generated from the title if left blank.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Stored UTC, displayed Africa/Lagos.
   */
  publishedAt?: string | null;
  /**
   * Which of the three sites publishes this.
   */
  site?: ('foundation' | 'dawah' | 'honey') | null;
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  author?: (number | null) | TeamMember;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedRemedies?: (number | Remedy)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  /**
   * URL segment. Generated from the title if left blank.
   */
  slug: string;
  honorific?: string | null;
  role: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL segment. Generated from the title if left blank.
   */
  slug: string;
  status: 'draft' | 'published';
  site: 'foundation' | 'dawah' | 'honey';
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  /**
   * How the person is credited. Use a category ("A student, Ede") unless consent to be named is recorded.
   */
  attribution: string;
  /**
   * Written consent to publish this quote is on file.
   */
  consentRecorded?: boolean | null;
  site?: ('foundation' | 'dawah' | 'honey') | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  site: 'foundation' | 'dawah' | 'honey';
  order?: number | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Zakat is a separate fund — filter by purpose before reporting any total.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: number;
  /**
   * Our internal reference.
   */
  reference: string;
  /**
   * Amount in kobo (integer). ₦1,000 = 100000 kobo.
   */
  amountKobo: number;
  /**
   * Zakat is ring-fenced: it has its own ledger and its own eligibility rules.
   */
  purpose: 'appeal' | 'zakat' | 'sadaqah' | 'general' | 'dawah-scholarship';
  appealRef?: (number | null) | Appeal;
  donorName?: string | null;
  donorEmail?: string | null;
  /**
   * Paystack subscription or standing transfer.
   */
  isRecurring?: boolean | null;
  /**
   * Donor asked not to be named publicly.
   */
  isAnonymous?: boolean | null;
  status: 'pending' | 'paid' | 'awaiting-transfer' | 'failed' | 'refunded';
  /**
   * Paystack transaction reference. Unique — this is what makes the webhook idempotent.
   */
  paystackRef?: string | null;
  channel?: ('paystack' | 'bank-transfer') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pledges".
 */
export interface Pledge {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  /**
   * Pledged amount per month, in kobo.
   */
  amountKobo: number;
  method: 'card' | 'transfer';
  purpose: 'empowerment' | 'zakat' | 'sadaqah';
  message?: string | null;
  /**
   * Consent to be contacted about the pledge. Unticked on the form.
   */
  consent: boolean;
  status: 'new' | 'active' | 'lapsed' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * Contains health data. Handle under the NDPA 2023.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistance-requests".
 */
export interface AssistanceRequest {
  id: number;
  name: string;
  phone: string;
  whatsapp?: string | null;
  email?: string | null;
  state?: string | null;
  lga?: string | null;
  category: 'medical' | 'financial' | 'shelter' | 'other';
  /**
   * In the applicant's own words.
   */
  need: string;
  hospital?: string | null;
  /**
   * Amount in kobo (integer). ₦1,000 = 100000 kobo.
   */
  amountRequestedKobo?: number | null;
  refereeName?: string | null;
  refereePhone?: string | null;
  /**
   * Hospital bill, diagnosis or similar, if supplied.
   */
  documents?: (number | Media)[] | null;
  /**
   * Consent to the foundation storing and verifying these details. Required, and unticked on the form.
   */
  consentToProcess: boolean;
  /**
   * SEPARATE consent to be named or photographed publicly. Off by default — nothing identifiable is published without it.
   */
  consentToBeNamed?: boolean | null;
  status: 'new' | 'verifying' | 'approved' | 'assisted' | 'declined';
  /**
   * Verification notes. Never published.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  title: string;
  /**
   * URL segment. Generated from the title if left blank.
   */
  slug: string;
  teacher?: (number | null) | Teacher;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * RRULE string, e.g. FREQ=MONTHLY;BYDAY=-1MO for the last Monday of the month. Times are Africa/Lagos.
   */
  recurrenceRule: string;
  /**
   * Handled explicitly by the recurrence engine.
   */
  recurrenceException?: ('none' | 'skip-second-sunday-when-last') | null;
  /**
   * 24-hour local time (Africa/Lagos). Unconfirmed for most classes.
   */
  startTime?: string | null;
  durationMinutes?: number | null;
  venue?: string | null;
  platform?: string | null;
  language?: ('yoruba' | 'english' | 'arabic' | 'mixed') | null;
  isFree?: boolean | null;
  recordings?:
    | {
        title: string;
        recordedOn?: string | null;
        audio?: (number | null) | Media;
        /**
         * YouTube or podcast link, if not hosted here.
         */
        externalUrl?: string | null;
        durationMinutes?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers".
 */
export interface Teacher {
  id: number;
  /**
   * Spelled exactly as in docs/01. Do not normalise the apostrophes.
   */
  name: string;
  /**
   * URL segment. Generated from the title if left blank.
   */
  slug: string;
  honorific?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  credentials?:
    | {
        credential: string;
        id?: string | null;
      }[]
    | null;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ambassadors".
 */
export interface Ambassador {
  id: number;
  name: string;
  /**
   * Not published on the leaderboard.
   */
  phone: string;
  email?: string | null;
  code: string;
  registeredAt: string;
  status: 'active' | 'suspended' | 'retired';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  reference: string;
  items: {
    product: number | Product;
    quantity: number;
    /**
     * Total litres for this line. Drives the 5 L minimum.
     */
    litres: number;
    /**
     * Price at the time of ordering, in kobo.
     */
    unitPriceKobo: number;
    id?: string | null;
  }[];
  customer: {
    name: string;
    phone: string;
    email?: string | null;
    address?: string | null;
  };
  /**
   * No prior confirmed purchase. Set by the attribution logic, not by hand.
   */
  isNewCustomer?: boolean | null;
  /**
   * First confirmed code wins; it is never reassigned afterwards.
   */
  referralCode?: string | null;
  /**
   * Amount in kobo (integer). ₦1,000 = 100000 kobo.
   */
  totalKobo: number;
  /**
   * Zones and rates still to be confirmed.
   */
  deliveryZone?: string | null;
  status: 'pending' | 'paid' | 'awaiting-transfer' | 'confirmed' | 'delivered' | 'cancelled' | 'refunded';
  /**
   * Unique — makes the payment webhook idempotent.
   */
  paystackRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  name?: string | null;
  /**
   * Explicit opt-in. The public form ships unticked — never pre-tick it.
   */
  consent: boolean;
  /**
   * When consent was given. Stored UTC.
   */
  consentTimestamp?: string | null;
  /**
   * Which page or campaign the subscriber came from.
   */
  source?: string | null;
  status: 'subscribed' | 'unsubscribed' | 'bounced';
  subscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  topic: 'general' | 'consultation' | 'donation' | 'media' | 'distributor' | 'course';
  subjectLine: string;
  message: string;
  /**
   * Inbox this submission is addressed to.
   */
  routedTo?: string | null;
  /**
   * Consent to be replied to. Unticked by default on the form.
   */
  consent: boolean;
  status?: ('new' | 'answered' | 'spam') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editors cannot see donations or orders. Shop managers handle the honey shop only.
   */
  role: 'admin' | 'editor' | 'shop-manager';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'appeals';
        value: number | Appeal;
      } | null)
    | ({
        relationTo: 'annual-reports';
        value: number | AnnualReport;
      } | null)
    | ({
        relationTo: 'remedies';
        value: number | Remedy;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'donations';
        value: number | Donation;
      } | null)
    | ({
        relationTo: 'pledges';
        value: number | Pledge;
      } | null)
    | ({
        relationTo: 'assistance-requests';
        value: number | AssistanceRequest;
      } | null)
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'teachers';
        value: number | Teacher;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'ambassadors';
        value: number | Ambassador;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appeals_select".
 */
export interface AppealsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isAnonymous?: T;
  category?: T;
  beneficiaryName?: T;
  anonymousLabel?: T;
  needDescription?: T;
  hospital?: T;
  targetAmountKobo?: T;
  raisedAmountKobo?: T;
  status?: T;
  openedDate?: T;
  closedDate?: T;
  photos?: T;
  updates?:
    | T
    | {
        date?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  closingReport?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "annual-reports_select".
 */
export interface AnnualReportsSelect<T extends boolean = true> {
  fiscalYear?: T;
  introduction?: T;
  quranVerse?:
    | T
    | {
        arabic?: T;
        translation?: T;
        reference?: T;
      };
  beneficiaries?:
    | T
    | {
        name?: T;
        date?: T;
        need?: T;
        hospital?: T;
        raisedKobo?: T;
        targetKobo?: T;
        id?: T;
      };
  surplusAssistances?:
    | T
    | {
        description?: T;
        amountKobo?: T;
        id?: T;
      };
  totalRaisedKobo?: T;
  beneficiaryCount?: T;
  closingNote?: T;
  pdfUpload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "remedies_select".
 */
export interface RemediesSelect<T extends boolean = true> {
  name?: T;
  arabicName?: T;
  transliteration?: T;
  slug?: T;
  quranVerse?:
    | T
    | {
        arabic?: T;
        translation?: T;
        reference?: T;
      };
  hadiths?:
    | T
    | {
        arabic?: T;
        translation?: T;
        source?: T;
        gradingNote?: T;
        id?: T;
      };
  ibnQayyimCommentary?: T;
  composition?: T;
  traditionalUses?: T;
  precautions?: T;
  isFree?: T;
  bookChapterRef?: T;
  relatedProduct?: T;
  featuredImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  site?: T;
  excerpt?: T;
  coverImage?: T;
  author?: T;
  body?: T;
  relatedRemedies?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  site?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  consentRecorded?: T;
  site?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  honorific?: T;
  role?: T;
  bio?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  site?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  reference?: T;
  amountKobo?: T;
  purpose?: T;
  appealRef?: T;
  donorName?: T;
  donorEmail?: T;
  isRecurring?: T;
  isAnonymous?: T;
  status?: T;
  paystackRef?: T;
  channel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pledges_select".
 */
export interface PledgesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  amountKobo?: T;
  method?: T;
  purpose?: T;
  message?: T;
  consent?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assistance-requests_select".
 */
export interface AssistanceRequestsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  state?: T;
  lga?: T;
  category?: T;
  need?: T;
  hospital?: T;
  amountRequestedKobo?: T;
  refereeName?: T;
  refereePhone?: T;
  documents?: T;
  consentToProcess?: T;
  consentToBeNamed?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  teacher?: T;
  description?: T;
  recurrenceRule?: T;
  recurrenceException?: T;
  startTime?: T;
  durationMinutes?: T;
  venue?: T;
  platform?: T;
  language?: T;
  isFree?: T;
  recordings?:
    | T
    | {
        title?: T;
        recordedOn?: T;
        audio?: T;
        externalUrl?: T;
        durationMinutes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers_select".
 */
export interface TeachersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  honorific?: T;
  bio?: T;
  credentials?:
    | T
    | {
        credential?: T;
        id?: T;
      };
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  volumeLitres?: T;
  packSize?: T;
  retailPriceKobo?: T;
  wholesalePriceKobo?: T;
  minWholesaleLitres?: T;
  images?: T;
  nafdacNumber?: T;
  inStock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ambassadors_select".
 */
export interface AmbassadorsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  code?: T;
  registeredAt?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  reference?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        litres?: T;
        unitPriceKobo?: T;
        id?: T;
      };
  customer?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        address?: T;
      };
  isNewCustomer?: T;
  referralCode?: T;
  totalKobo?: T;
  deliveryZone?: T;
  status?: T;
  paystackRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  consentRecorded?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  consent?: T;
  consentTimestamp?: T;
  source?: T;
  status?: T;
  subscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  topic?: T;
  subjectLine?: T;
  message?: T;
  routedTo?: T;
  consent?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}